version: '3.8'

services:
  flask:
    container_name: flask
    build: .
    command: gunicorn -b 0.0.0.0:5000 wsgi:app \
      --preload=True \
      --worker-class=eventlet \
      --workers=5 \
      --threads=4 \
      --timeout 120 \
      --log-level=debug \
      --log-file - \
      --max-requests=5120 \
      --max-requests-jitter=1000 \
      --worker-tmp-dir=/dev/shm
    volumes:
      - ./src:/src
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    container_name: PG
    image: postgres
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: example
    expose:
      - "5432"
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db:
    driver: local

networks:
  backend:
    driver: bridge
